version: '3'
services:

  db:
    image: mysql:5.7
    ports:
      - 3303:3303
    environment: 
      - MYSQL_ROOT_PASSWORD=parola
  # mongo:
  #   image: mongo:3.6
  #   ports:
  #     - 27017:27017

#  server:
#    build: .
#    ports:
#      - 3000:3000
